imports_granularity = "module"
group_imports = "StdExternalCrate"

chain_width = 90

max_width = 120
tab_spaces = 4

struct_lit_width = 90
struct_field_align_threshold = 20
use_field_init_shorthand = true
fn_call_width = 40
